const text="  In the name of God ";
console.log(text.length);
console.log(text.toLocaleLowerCase());
console.log(text.toUpperCase());
console.log(text.split(" "));
console.log(text.trim());
console.log(text.charAt(4));
console.log(text.charCodeAt(0));
console.log(text.indexOf("f"));
console.log(text.lastIndexOf("f"));
